exp_id: 53-unet_google_dropout_0.2_no_ss
datadir: /data/stephan/WeatherBench/5.625deg/
model_save_dir: /home/rasp/data/myWeatherBench/predictions/saved_models/
pred_save_dir: /home/rasp/data/myWeatherBench/predictions/
var_dict: {'geopotential': ('z', [250, 500, 850]), 'temperature': ('t', [250, 500, 850]), 'u_component_of_wind': ('u', [250, 500, 850]), 'v_component_of_wind': ('v', [250, 500, 850]), 'constants': ['lsm','orography','lat2d']}
output_vars: [z_500, t_850]
filters: [64, 128, 256, 512]
kernels: [0]
lead_time: 72
lr: 0.5e-4
early_stopping_patience: 10
reduce_lr_patience: 5
min_es_delta: 0.0002
data_subsample: 1
norm_subsample: 60000
bn_position: post
dropout: 0.2
network: unet_google